faqapp/urls.py
from django.contrib import admin
from django.urls import path, include
from questions.views import landing_page

urlpatterns = [
    path('', landing_page, name="landing"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls', namespace='questions')),
]

questions/urls.py
from django.urls import path
from .views import *


app_name = 'questions'

urlpatterns = [
    path('', QuestionListView.as_view(), name='index'),
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('like/<int:pk>', LikeView, name='like'),
    path('<int:pk>/details/', QuestionDetailView.as_view(), name='details'),
    path('<int:pk>/answer', CommentView.as_view(), name='answer'),
    path('<int:pk>/likeanswer', LikeAnswer, name='like-answer'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('<int:pk>/delete/', question_delete, name='delete'),
    path('<int:pk>/update/', question_update, name='update'),
]

questions/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, editable=False, on_delete=models.CASCADE)
    question = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='questions', blank=True)
    is_liked = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    @property
    def likes_count(self):
        return self.likes.count()

class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    user = models.ForeignKey(User, editable=False, on_delete=models.CASCADE)
    answer = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='answers', blank=True)
    is_liked = models.BooleanField(default=False)

    def __str__(self):
        return f"Answer: {self.question}-{self.user}"

    @property
    def likes_count(self):
        return self.likes.count()

questions/forms.py
from django import forms
from .models import *

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question',)

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

        widgets = {
         'answer': forms.Textarea(attrs={'cols': 10, 'rows': 2}),
         }

questions/views.py
from django.db.models.query_utils import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import *
from .forms import *
from django.http import HttpResponseRedirect
from questions.models import Answer, Question
from django.core.exceptions import PermissionDenied

def landing_page(request):
    return render(request, "landing.html")

def LikeView(request, pk):
    question = get_object_or_404(Question, id=request.POST.get('question_id'))
    if question.likes.filter(id=request.user.id).exists():
        question.likes.remove(request.user)
        question.is_liked = False
        question.save()
    else:
        question.likes.add(request.user)
        question.is_liked = True
        question.save()
    return HttpResponseRedirect(reverse('questions:index'))

def LikeAnswer(request, pk):
    answer = get_object_or_404(Answer, id=request.POST.get('answer_id'))
    if answer.likes.filter(id=request.user.id).exists():
        answer.likes.remove(request.user)
        answer.is_liked = False
        answer.save()
    else:
        answer.likes.add(request.user)
        answer.is_liked = True
        answer.save()
    return HttpResponseRedirect(reverse("questions:index"))

def question_delete(request, pk):
    question = Question.objects.get(id=pk)
    if request.user.is_staff or request.user == question.author:
        question.delete()
    else:
        raise PermissionDenied("Access forbidden 403. Are you the author of this question?")
    return redirect('questions:index')

class QuestionCreateView(CreateView):
    model = Question
    template_name = "question_create.html"
    form_class = QuestionForm

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("questions:index")

class QuestionListView(ListView):
    model = Question
    template_name = 'index.html'
    paginate_by = 8
    ordering = ['-timestamp']

class QuestionDetailView(DetailView):
    model = Question
    template_name = "question_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AnswerForm()
        return context

class CommentView(CreateView):
    model = Answer
    form_class = AnswerForm

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        pk = self.kwargs.get('pk')
        question = Question.objects.get(id=pk)
        return reverse("questions:details", kwargs={'pk': question.pk})

class SearchResultsView(ListView):
    model = Question
    template_name = 'index.html'
    paginate_by = 20
    ordering = ['-timestamp']

    def get_queryset(self):  # new
        query = self.request.GET.get('q')
        if query:
            q_list = Question.objects.filter(
                Q(question__icontains=query) | Q(id__icontains=query) | Q(author__username__icontains=query)
            ).order_by('-timestamp')
            return q_list
        return Question.objects.all().order_by('-timestamp')

def question_update(request, pk):
    question = Question.objects.get(id=pk)
    form = QuestionForm(instance=question)
    if request.user.is_staff or request.user == question.author:
        if request.method == 'POST':
            form = QuestionForm(request.POST, instance=question)
            if form.is_valid():
                form.save()
                return redirect('questions:index')
    else:
        raise PermissionDenied("Access forbidden 403. Are you the author of this question?")
    context = {
        'form': form,
        'question': question
    }
    return render(request, 'question_update.html', context)

questions/templates/index.html
{% extends "base.html" %}

{% block title %}
  home
{% endblock title %}

{% block content %}
<br><br>
  <h1><a href="{% url 'questions:create' %}" class="btn btn-primary btn-sm btn-block">Ask something to the community</a></h1>
  <br><br>
<div class="text-left">
  <h4 class="text-muted">Looking for something specific?</h4>
  <form action="{% url 'questions:search' %}" method="get">
    <input type="search" name="q" class="form-control"><br/>
  </form>
</div>
  <h3>Or explore the previous asked questions below.</h3>
<div class="container">
  {% for question in object_list %}
    <hr>
    <div class="row">
      <div class="col-lg-8">{{question.question}}</div>
      <div class="col-lg-2 text-success"><small>{{question.timestamp}}</small></div>
      <div class="col-lg-2" style="color: black;"><strong>{{question.author | title}}</strong></div>
    </div>
    <form action="{% url 'questions:like' question.pk %}" method="post">
      {% csrf_token %}
    <div class="row">
      {% if user in question.likes.all %}
      <div class="col-lg-1 mt-2">
        <label>
        <input type="submit" name="question_id" value="{{question.id}}" style="display: none;">
        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-heart-fill text-danger" viewBox="0 0 16 16" style="cursor: pointer;">
          <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
        </svg>
      </input>
    </label>
    </div>
    {% else %}
      <div class="col-lg-1 mt-2">
        <label>
        <input type="submit" name="question_id" value="{{question.id}}" style="display: none;">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16" style="cursor: pointer;">
        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
       </svg>
      </input>
    </label>
    </div>
    {% endif %}
    <div class="col-lg-3 mt-2 text-muted"><strong class="mr-2" style="color: black;">{{question.likes_count}}</strong> <small>people like this question.</small> </div>
    <div class="col-lg-3 mt-2 text-primary"><small> <a href="{% url 'questions:details' question.pk %}" style="text-decoration: none;"> Check all the answers... </a></small></div>
    {% if request.user.is_staff or request.user == question.author %}
    <div class="col-lg-4 mt-2 text-primary text-right"><small><a href="{% url 'questions:update' question.id %}">Update</a></small><strong class="text-muted"> | <small></strong><a href="{% url 'questions:delete' question.id %}" onclick="return confirm('Are you sure to delete this question?');" class="text-danger">Delete</a></small></div>
    {% endif %}
    </div>
    </form>
    <hr>
  {% endfor %}
</div>
<br>
<br>
<div class="pagination justify-content-center">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1" class="btn btn-sm btn-secondary">&laquo; First</a>
          <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-secondary">Previous</a>
      {% endif %}

      <span class="current mr-2 ml-2 text-primary">
         <small>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} </small>
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-primary">Next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-sm btn-primary">Last &raquo;</a>
      {% endif %}
  </span>
</div>
<br><br>
{% endblock content %}

questions/templates/landing.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>
  <body>
    
<div class="container text-center mt-5">
    <h1 style="font-family: 'SF-Pro Bold', sans-serif;">Question/Answer App.</h1>
    <p class="lead font-weight-normal">This website provides <b>python-programming</b> related questions and answers if you feel like you belong here create an account and enjoy.</p>
    <a class="btn btn-primary" href="{% url 'account_login' %}">Let's Go</a>
</div>
  </body>
</html>

questions/templates/question_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  ask
{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success col-4">Ask</button>
</form>
{% endblock content %}

questions/templates/question_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  question details
{% endblock title %}

{% block content %}
<h1 style="font-family: 'SF-Pro Bold', sans-serif;">Question ID: {{question.id}}</h1>
  <p class="text-info">{{question.question}}</p>
  <h3 style="font-family: 'SF-Pro Bold', sans-serif;">Most recent answers:</h3>
  <br/>
    {% if not question.answers.all %}
    <h5 class="text-muted">No answers yet...</h5>
    {% else %}
    {% for answer in question.answers.all %}
    <hr>
    <div class="row">
        <div class="col-lg-1"><strong>{{answer.user | title}}</strong></div>
        <div class="col-lg-3 text-primary">{{answer.timestamp}}</div>
        <div class="col-lg-8" style="color: black;"><small>{{answer.answer}}</small></div>
    </div>
    <form action="{% url 'questions:like-answer' answer.pk %}" method="post">
        {% csrf_token %}
      <div class="row">
        {% if user in answer.likes.all %}
        <div class="col-lg-1 mt-2">
          <label>
          <input type="submit" name="answer_id" value="{{answer.id}}" style="display: none;">
          <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-heart-fill text-danger" viewBox="0 0 16 16" style="cursor: pointer;">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
        </input>
      </label>
      </div>
      {% else %}
        <div class="col-lg-1 mt-2">
          <label>
          <input type="submit" name="answer_id" value="{{answer.id}}" style="display: none;">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16" style="cursor: pointer;">
          <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
         </svg>
        </input>
      </label>
      </div>
      {% endif %}
      <div class="col-lg-3 mt-2 text-muted"><strong class="mr-2" style="color: black;">{{answer.likes_count}}</strong> <small>people like this answer.</small> </div>
      </div>
      </form>
    <hr>
    {% endfor %}
    {% endif %}
    <br>
  <form action="{% url 'questions:answer' question.pk %}" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <div class="text-muted text-center">
    <button type="submit" class="btn btn-primary col-md-4"> <span class="fas fa-comments"></span>Answer</button>
  </form>
   </div>
<br><br><br>
{% endblock content %}

questions/templates/question_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  modify question
{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success col-4">Submit</button>
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

    <title>{% block title %}
    {% endblock title %}@QaApp</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'questions:index' %}">  <img src="{% static 'img/python.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                Python FAQ</a>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'questions:index' %}">Home</a>
                  </li>
                </ul>
              </div>
              <a href="{% url 'account_logout' %}" class="misen nav-item">Logout</a>
            </div>
          </nav>
    </header>
    <div class="container mt-5">
        {% block content %}
          
        {% endblock content %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/datatables.min.js' %}"></script>
</body>
</html>